# Generated by Django 4.2.17 on 2024-12-31 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_user_delete_usersubscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='membership_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
