# Generated by Django 4.2.17 on 2024-12-29 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_cartitem_catalogbookgenre_delete_accessrestriction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='books',
        ),
    ]
