# Generated by Django 4.2.17 on 2025-01-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content_file',
            field=models.FileField(blank=True, null=True, upload_to='books/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='content_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
