# Generated by Django 4.2.17 on 2024-12-15 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_author_birth_date_alter_author_nationality'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='catalog.book'),
        ),
        migrations.AddField(
            model_name='book',
            name='authors_name',
            field=models.CharField(default='Unknown Author', max_length=255),
        ),
    ]
