# Generated by Django 4.2.17 on 2025-01-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_book_content_file_alter_book_content_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'isbn')},
        ),
    ]
