# Generated by Django 4.2.17 on 2024-12-16 00:00

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_book_author_alter_author_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_link', models.URLField(blank=True, null=True, validators=[catalog.models.validate_url_or_local_path])),
            ],
        ),
    
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='catalog.book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='access_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='content_link',
            field=models.URLField(blank=True, null=True, validators=[catalog.models.validate_url_or_local_path]),
        ),
        migrations.AlterField(
            model_name='book',
            name='popularity_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='read_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
