# Generated by Django 4.2.17 on 2024-12-16 00:10

import catalog.models
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_yourmodel_remove_book_author_alter_author_books_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='catalog.book'),
        ),
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_link', models.URLField(blank=True, null=True, validators=[catalog.models.validate_url_or_local_path])),
            ],
        ),
    ]
