# Generated by Django 4.2.17 on 2024-12-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_book_author_alter_book_rent_price'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
