# Generated by Django 4.2.17 on 2024-12-16 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_book_author_book_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='books',
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors_name',
        ),
    ]
